# Generated by Django 4.2.3 on 2023-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_discount',
            field=models.IntegerField(default=0),
        ),
    ]
