# Generated by Django 4.2.3 on 2023-08-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_selling_price',
            new_name='total_price',
        ),
    ]
