# Generated by Django 4.2.3 on 2023-08-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_total_selling_price_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_discount',
            new_name='discount_price',
        ),
    ]
