# Generated by Django 4.2.3 on 2023-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_total_discount_price_cartitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_actual_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
