# Generated by Django 4.2.3 on 2023-09-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_total_actual_price_cart_total_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
