# Generated by Django 4.2.3 on 2023-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_total_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
