# Generated by Django 4.2.3 on 2023-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='new',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storeimages/'),
        ),
    ]
