# Generated by Django 4.2.3 on 2023-08-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='variant',
            name='original_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
