# Generated by Django 4.2.3 on 2023-08-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
