# Generated by Django 4.2.3 on 2023-09-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
