# Generated by Django 4.2.3 on 2023-08-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.variant'),
        ),
    ]
