# Generated by Django 4.2.3 on 2023-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_images_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.AddField(
            model_name='variant',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
