# Generated by Django 4.2.3 on 2023-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_images_name_remove_variant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='mainimage',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
