# Generated by Django 4.2.3 on 2023-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_variant_mainimage_variant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='image',
            new_name='mainimage',
        ),
    ]
