# Generated by Django 4.2.3 on 2023-09-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_no',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
