# Generated by Django 4.2.3 on 2023-09-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variant_product'),
        ('user', '0007_orderitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='store.variant'),
        ),
    ]
