# Generated by Django 4.2.3 on 2023-09-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed')], default='pending', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='user.order'),
        ),
    ]
