# Generated by Django 4.2.3 on 2023-09-19 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_created_at_order_message_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_no',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 11, 49, 5, 397589)),
        ),
    ]
