# Generated by Django 4.2.3 on 2023-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_order_created_at_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
