# Generated by Django 4.2.3 on 2023-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_review_product_variant_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
    ]
