# Generated by Django 4.2.3 on 2023-10-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_order_coupon_discount_order_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_actual_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_count',
        ),
    ]
