# Generated by Django 4.2.3 on 2023-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_rename_total_price_orderitem_total_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
