# Generated by Django 4.2.3 on 2023-10-10 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 13, 6, 32, 41, 840752, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
