# Generated by Django 4.2.3 on 2023-10-18 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 21, 7, 15, 48, 598730, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
