# Generated by Django 4.2.3 on 2023-10-30 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 2, 9, 9, 45, 979224, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
