# Generated by Django 4.2.3 on 2023-11-10 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 13, 4, 44, 17, 139206, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
