# Generated by Django 4.2.3 on 2023-11-10 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 13, 5, 13, 46, 946049, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
